# Generated by Django 3.1.1 on 2020-10-21 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_orders_orderupdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderUpdate',
        ),
    ]
